#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export EDITOR='nvim'
export TERMINAL='alacritty'
export BROWSER='firefox'
export TERM=xterm-256color #??
export PATH="$HOME/.local/bin":$PATH
#export MANPAGER="sh -c 'col -bx | batcat --color=always --decorations=always --pagine --tabs=2 -l man -p"
export MANWIDTH=999
#export PATH=$PATH:~/.flutter/bin:~/Android/Sdk/emulator:~/.npm-global/bin:~/.flutter/.pub-cache/bin

export LSCOLORS="Gxfxcxdxbxegedabagacad"

## History file configuration
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
[ "$HISTSIZE" -lt 50000 ] && HISTSIZE=50000
[ "$SAVEHIST" -lt 10000 ] && SAVEHIST=10000

# eval "`pip completion --zsh`"
