#!/bin/sh
export EDITOR='nvim'
export TERMINAL='alacritty'
export BROWSER='firefox'
export TERM=xterm-256color #??
export VISUAL='code-insiders'
export ANDROID_SDK="$HOME/Android/Sdk"
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.scripts":$PATH
export PATH="$HOME/flutter/bin":$PATH
#export PATH="$HOME/flutter/.pub_cache/bin":$PATH
export PATH="$ANDROID_SDK/tools":$PATH
export PATH="$ANDROID_SDK/tools/bin":$PATH
export PATH="$ANDROID_SDK/platform-tools":$PATH
export PATH="$ANDROID_SDK/emulator":$PATH
export PATH="$ANDROID_SDK/tools/bin/sdkmanager":$PATH
#export PATH="$HOME/.npm-global/bin":$PATH
export PATH="$HOME/.cargo/bin":$PATH
export MANPAGER="sh -c 'col -bx | batcat --color=always --decorations=always --tabs=2 -l man -p'"
export MANWIDTH=999

export LSCOLORS="Gxfxcxdxbxegedabagacad"

## History file configuration
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=50000
export SAVEHIST=10000
setopt INC_APPEND_HISTORY
#setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE # if the command starts with a space it wont be saved in the history
# eval "`pip completion --zsh`"

### PATH
#if [ -d "$HOME/.bin" ] ;
#  then PATH="$HOME/.bin:$PATH"
#fi
